// <auto-generated />
using System;
using BilgewaterTrade.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BilgewaterTrade.DataAccess.Migrations
{
    [DbContext(typeof(BilgewaterTradeDbContext))]
    [Migration("20260817162234_RealmTable")]
    partial class RealmTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BilgewaterTrade.Core.Models.AuctionHouseSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Realm")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuctionHouseSnapshots");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.CommodityListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionHouseSnapshotId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLeft")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceCopper")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuctionHouseSnapshotId");

                    b.HasIndex("ItemId");

                    b.ToTable("CommodityListings");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCommodity")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.Realm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectedRealmId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.RealmListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionHouseSnapshotId")
                        .HasColumnType("integer");

                    b.Property<long?>("BuyoutCopper")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLeft")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionHouseSnapshotId");

                    b.HasIndex("ItemId");

                    b.ToTable("RealmListings");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.CommodityListing", b =>
                {
                    b.HasOne("BilgewaterTrade.Core.Models.AuctionHouseSnapshot", "AuctionHouseSnapshot")
                        .WithMany()
                        .HasForeignKey("AuctionHouseSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgewaterTrade.Core.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionHouseSnapshot");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BilgewaterTrade.Core.Models.RealmListing", b =>
                {
                    b.HasOne("BilgewaterTrade.Core.Models.AuctionHouseSnapshot", "AuctionHouseSnapshot")
                        .WithMany()
                        .HasForeignKey("AuctionHouseSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgewaterTrade.Core.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionHouseSnapshot");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
